services:
  ollama:
    image: ollama/ollama:latest
    container_name: flood-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flood-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - flood-db:/app
    environment:
      - FLASK_ENV=production
      - OLLAMA_URL=http://ollama:11434
      - DATABASE_PATH=/app/flood_data.db
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/test"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flood-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama-data:
    driver: local
  flood-db:
    driver: local

networks:
  default:
    name: flood-network
